-- MySQL Script generated by MySQL Workbench
-- Mon Feb 15 00:34:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresaa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresaa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresaa` ;
USE `empresaa` ;

-- -----------------------------------------------------
-- Table `empresaa`.`lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`lugar` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `categoriaSocioEconomica` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `fk_lugar` INT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_lugar_lugar1_idx` (`fk_lugar` ASC) VISIBLE,
  CONSTRAINT `fk_lugar_lugar1`
    FOREIGN KEY (`fk_lugar`)
    REFERENCES `empresaa`.`lugar` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`nivel_economico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`nivel_economico` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`ocupacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`ocupacion` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`nivel_academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`nivel_academico` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`dato_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`dato_usuario` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(45) NOT NULL,
  `primerNombre` VARCHAR(45) NOT NULL,
  `segundoNombre` VARCHAR(45) NOT NULL,
  `primerApellido` VARCHAR(45) NOT NULL,
  `segundoApellido` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(20) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `estadoCivil` VARCHAR(45) NOT NULL,
  `disponibilidadEnLinea` VARCHAR(45) NOT NULL,
  `conCuantasPersonasVive` VARCHAR(45) NOT NULL,
  `medio_comunicacion` VARCHAR(45) NULL,
  `estado` VARCHAR(20) NOT NULL,
  `fk_nivelEconomico` INT NOT NULL,
  `fk_lugar` INT NOT NULL,
  `fk_ocupacion` INT NOT NULL,
  `fk_nivelAcademico` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_dato_usuario_nivel_economico2_idx` (`fk_nivelEconomico` ASC) VISIBLE,
  INDEX `fk_dato_usuario_lugar2_idx` (`fk_lugar` ASC) VISIBLE,
  INDEX `fk_dato_usuario_ocupacion2_idx` (`fk_ocupacion` ASC) VISIBLE,
  INDEX `fk_dato_usuario_nivel_academico2_idx` (`fk_nivelAcademico` ASC) VISIBLE,
  CONSTRAINT `fk_dato_usuario_nivel_economico2`
    FOREIGN KEY (`fk_nivelEconomico`)
    REFERENCES `empresaa`.`nivel_economico` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dato_usuario_lugar2`
    FOREIGN KEY (`fk_lugar`)
    REFERENCES `empresaa`.`lugar` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dato_usuario_ocupacion2`
    FOREIGN KEY (`fk_ocupacion`)
    REFERENCES `empresaa`.`ocupacion` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dato_usuario_nivel_academico2`
    FOREIGN KEY (`fk_nivelAcademico`)
    REFERENCES `empresaa`.`nivel_academico` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`hijo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`hijo` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `fechaNacimiento` DATE NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `fk_datoUsuario` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_hijo_dato_usuario2_idx` (`fk_datoUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_hijo_dato_usuario2`
    FOREIGN KEY (`fk_datoUsuario`)
    REFERENCES `empresaa`.`dato_usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`telefono` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `fk_datoUsuario` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_telefono_dato_usuario2_idx` (`fk_datoUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_telefono_dato_usuario2`
    FOREIGN KEY (`fk_datoUsuario`)
    REFERENCES `empresaa`.`dato_usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`rol` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`usuario` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `codigoRecuperacion` VARCHAR(45) NULL,
  `token` VARCHAR(45) NULL,
  `estado` VARCHAR(20) NOT NULL,
  `fk_rol` INT NOT NULL,
  `fk_datoUsuario` INT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_usuario_rol2_idx` (`fk_rol` ASC) VISIBLE,
  INDEX `fk_usuario_dato_usuario2_idx` (`fk_datoUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol2`
    FOREIGN KEY (`fk_rol`)
    REFERENCES `empresaa`.`rol` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_dato_usuario2`
    FOREIGN KEY (`fk_datoUsuario`)
    REFERENCES `empresaa`.`dato_usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`marca` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`categoria` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`subcategoria` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `fk_categoria` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_subcategoria_categoria2_idx` (`fk_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_subcategoria_categoria2`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `empresaa`.`categoria` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`producto` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `fk_marca` INT NOT NULL,
  `fk_subcategoria` INT NOT NULL,
  `fk_usuario` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_producto_marca2_idx` (`fk_marca` ASC) VISIBLE,
  INDEX `fk_producto_subcategoria2_idx` (`fk_subcategoria` ASC) VISIBLE,
  INDEX `fk_producto_usuario2_idx` (`fk_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_producto_marca2`
    FOREIGN KEY (`fk_marca`)
    REFERENCES `empresaa`.`marca` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_subcategoria2`
    FOREIGN KEY (`fk_subcategoria`)
    REFERENCES `empresaa`.`subcategoria` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_usuario2`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `empresaa`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`solicitud_estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`solicitud_estudio` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `descripcionSolicitud` VARCHAR(255) NOT NULL,
  `generoPoblacional` VARCHAR(45) NOT NULL,
  `fechaPeticion` DATE NOT NULL,
  `edadMinimaPoblacion` VARCHAR(45) NOT NULL,
  `edadMaximaPoblacion` VARCHAR(45) NOT NULL,
  `estatus` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `conCuantasPersonasVive` VARCHAR(45) NULL,
  `disponibilidadEnLinea` VARCHAR(45) NULL,
  `fk_nivelEconomico` INT NOT NULL,
  `fk_ocupacion` INT NULL,
  `fk_usuario` INT NOT NULL,
  `fk_producto` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_solicitud_estudio_nivel_economico2_idx` (`fk_nivelEconomico` ASC) VISIBLE,
  INDEX `fk_solicitud_estudio_ocupacion2_idx` (`fk_ocupacion` ASC) VISIBLE,
  INDEX `fk_solicitud_estudio_usuario2_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_solicitud_estudio_producto2_idx` (`fk_producto` ASC) VISIBLE,
  CONSTRAINT `fk_solicitud_estudio_nivel_economico2`
    FOREIGN KEY (`fk_nivelEconomico`)
    REFERENCES `empresaa`.`nivel_economico` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_estudio_ocupacion2`
    FOREIGN KEY (`fk_ocupacion`)
    REFERENCES `empresaa`.`ocupacion` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_estudio_usuario2`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `empresaa`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_estudio_producto2`
    FOREIGN KEY (`fk_producto`)
    REFERENCES `empresaa`.`producto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`estudio` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NULL,
  `estatus` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `conclusion` VARCHAR(255) NULL,
  `fk_solicitudEstudio` INT NOT NULL,
  `fk_usuario` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_estudio_solicitud_estudio2_idx` (`fk_solicitudEstudio` ASC) VISIBLE,
  INDEX `fk_estudio_usuario2_idx` (`fk_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_estudio_solicitud_estudio2`
    FOREIGN KEY (`fk_solicitudEstudio`)
    REFERENCES `empresaa`.`solicitud_estudio` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudio_usuario2`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `empresaa`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`presentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`presentacion` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `caracteristicas` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`tipo` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`pregunta_encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`pregunta_encuesta` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `tipoPregunta` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `fk_subcategoria` INT NOT NULL,
  `fk_usuario` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_pregunta_encuesta_subcategoria2_idx` (`fk_subcategoria` ASC) VISIBLE,
  INDEX `fk_pregunta_encuesta_usuario2_idx` (`fk_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_pregunta_encuesta_subcategoria2`
    FOREIGN KEY (`fk_subcategoria`)
    REFERENCES `empresaa`.`subcategoria` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pregunta_encuesta_usuario2`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `empresaa`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`respuesta_pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`respuesta_pregunta` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `fk_preguntaEncuesta` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_respuesta_pregunta_pregunta_encuesta2_idx` (`fk_preguntaEncuesta` ASC) VISIBLE,
  CONSTRAINT `fk_respuesta_pregunta_pregunta_encuesta2`
    FOREIGN KEY (`fk_preguntaEncuesta`)
    REFERENCES `empresaa`.`pregunta_encuesta` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`pregunta_estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`pregunta_estudio` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(255) NULL,
  `estado` VARCHAR(20) NOT NULL,
  `fk_estudio` INT NOT NULL,
  `fk_preguntaEncuesta` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_estudio_has_pregunta_encuesta_pregunta_encuesta2_idx` (`fk_preguntaEncuesta` ASC) VISIBLE,
  INDEX `fk_estudio_has_pregunta_encuesta_estudio2_idx` (`fk_estudio` ASC) VISIBLE,
  CONSTRAINT `fk_estudio_has_pregunta_encuesta_estudio2`
    FOREIGN KEY (`fk_estudio`)
    REFERENCES `empresaa`.`estudio` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudio_has_pregunta_encuesta_pregunta_encuesta2`
    FOREIGN KEY (`fk_preguntaEncuesta`)
    REFERENCES `empresaa`.`pregunta_encuesta` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`respuesta` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `respuestaSimple` VARCHAR(255) NULL,
  `respuestaMultiple` VARCHAR(255) NULL,
  `respuestaAbierta` VARCHAR(255) NULL,
  `escala` VARCHAR(255) NULL,
  `verdaderoFalso` VARCHAR(255) NULL,
  `fk_usuario` INT NOT NULL,
  `fk_preguntaEstudio` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_respuesta_usuario1_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_respuesta_pregunta_estudio1_idx` (`fk_preguntaEstudio` ASC) VISIBLE,
  CONSTRAINT `fk_respuesta_usuario1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `empresaa`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuesta_pregunta_estudio1`
    FOREIGN KEY (`fk_preguntaEstudio`)
    REFERENCES `empresaa`.`pregunta_estudio` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`region_estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`region_estudio` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(20) NOT NULL,
  `fk_lugar` INT NOT NULL,
  `fk_solicitudEstudio` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_lugar_has_solicitud_estudio_solicitud_estudio2_idx` (`fk_solicitudEstudio` ASC) VISIBLE,
  INDEX `fk_lugar_has_solicitud_estudio_lugar2_idx` (`fk_lugar` ASC) VISIBLE,
  CONSTRAINT `fk_lugar_has_solicitud_estudio_lugar2`
    FOREIGN KEY (`fk_lugar`)
    REFERENCES `empresaa`.`lugar` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lugar_has_solicitud_estudio_solicitud_estudio2`
    FOREIGN KEY (`fk_solicitudEstudio`)
    REFERENCES `empresaa`.`solicitud_estudio` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`producto_presentacion_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`producto_presentacion_tipo` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(20) NOT NULL,
  `fk_producto` INT NOT NULL,
  `fk_presentacion` INT NOT NULL,
  `fk_tipo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_producto_presentacion_producto1_idx` (`fk_producto` ASC) VISIBLE,
  INDEX `fk_producto_presentacion_presentacion1_idx` (`fk_presentacion` ASC) VISIBLE,
  INDEX `fk_producto_presentacion_tipo_tipo1_idx` (`fk_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_producto_presentacion_producto1`
    FOREIGN KEY (`fk_producto`)
    REFERENCES `empresaa`.`producto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_presentacion_presentacion1`
    FOREIGN KEY (`fk_presentacion`)
    REFERENCES `empresaa`.`presentacion` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_presentacion_tipo_tipo1`
    FOREIGN KEY (`fk_tipo`)
    REFERENCES `empresaa`.`tipo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaa`.`poblacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaa`.`poblacion` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `fk_usuario` INT NOT NULL,
  `fk_estudio` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_poblacion_usuario1_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_poblacion_estudio1_idx` (`fk_estudio` ASC) VISIBLE,
  CONSTRAINT `fk_poblacion_usuario1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `empresaa`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poblacion_estudio1`
    FOREIGN KEY (`fk_estudio`)
    REFERENCES `empresaa`.`estudio` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
